# Generated by Django 4.0.3 on 2022-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_remove_hijos_id_remove_padres_id_alter_hijos_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hijos',
            name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='fecha_de_nacimiento',
        ),
        migrations.AddField(
            model_name='hijos',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padres',
            name='edad',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
